version: '3'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - attitude_classifier

  attitude_classifier:
    build: ./attitude_classifier
    container_name: attitude_classifier
